      DOUBLE PRECISION barn, aml, aml2, al2, amt
      DOUBLE PRECISION pi, pi2, alfa, amp, amh, amhh, amhu, ampi
      DOUBLE PRECISION amp2, ap, ap2, amc2, amlep(2)
      INTEGER isf20, i2(8), i1(8)

      DATA barn/0.389379d+6/
      DATA pi/3.1415926d0/
      DATA alfa/0.729735d-2/
      DATA amp/0.938272d0/
      DATA ampi/0.1395675d0/
      DATA amlep/0.511000d-3,0.10565d0/
      DATA isf20/4/
      DATA i2/1,1,1,1,1,1,1,1/
      DATA i1/3,3,3,3,3,3,3,3/

      COMMON /consts/ amhh, amhu, amh, ap, ap2, amp2, amc2, pi2, aml,
     .aml2, al2, amt
